import { ArrowRight, CalendarDays, FileCheck2, LoaderCircle, TrendingUp } from "lucide-react";
import { NotificationCenter } from "@/components/NotificationCenter";
import { trpc } from "@/lib/trpc";

export default function WeeklySummaryPage() {
  const summaryQuery = trpc.program.roadmap.weeklySummary.useQuery();
  const summary = summaryQuery.data;

  return (
    <div className="site-shell min-h-screen bg-paper text-ink" dir="rtl">
      <header className="site-header site-header--scrolled flex items-center justify-between border-b border-line bg-white/90 px-8 py-4 backdrop-blur-md">
        <strong className="font-kufi text-falaj-deep">ملخص المنصة الأسبوعي</strong>
        <div className="flex items-center gap-3"><NotificationCenter /><a href="/roadmap" className="flex items-center gap-1 text-xs font-bold text-falaj hover:underline">العودة لخارطة الطريق <ArrowRight size={14} /></a></div>
      </header>
      <main className="mx-auto max-w-5xl px-6 py-16">
        <section className="mb-8 rounded-3xl border border-line bg-white p-8 md:p-10"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-falaj/20 bg-falaj/10 px-3 py-1 text-xs font-bold text-falaj"><CalendarDays size={14} /> آخر سبعة أيام</div><h1 className="font-kufi text-3xl font-extrabold text-falaj-deep">ملخص التغييرات الأسبوعي</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted">عرض تشغيلي مختصر لتحديثات مراحل خارطة الطريق والإصدارات المنشورة للمستثمرين خلال الأسبوع الأخير.</p></section>
        {summaryQuery.isLoading && <div className="rounded-2xl border border-line bg-white p-8 text-center text-sm text-muted"><LoaderCircle className="ml-2 inline animate-spin" size={16} /> يجري إعداد الملخص.</div>}
        {summaryQuery.error && <div className="rounded-2xl border border-line bg-white p-8 text-center text-sm text-muted">تعذر تحميل الملخص الأسبوعي حالياً.</div>}
        {summary && <><section className="mb-6 grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border border-line bg-white p-5"><div className="mb-2 flex items-center gap-2 text-falaj"><TrendingUp size={18} /><span className="text-xs font-bold">تحديثات التقدم</span></div><strong className="font-mono text-3xl text-falaj-deep">{summary.progressUpdates.length}</strong><p className="mt-2 text-xs text-muted">تعديلات موثقة على مراحل خارطة الطريق.</p></article><article className="rounded-2xl border border-line bg-white p-5"><div className="mb-2 flex items-center gap-2 text-falaj"><FileCheck2 size={18} /><span className="text-xs font-bold">إصدارات منشورة</span></div><strong className="font-mono text-3xl text-falaj-deep">{summary.publishedVersions.length}</strong><p className="mt-2 text-xs text-muted">إصدارات مواصفات متاحة للمستثمرين.</p></article></section><section className="grid gap-6 lg:grid-cols-2"><article className="rounded-3xl border border-line bg-white p-6"><h2 className="mb-4 flex items-center gap-2 font-kufi text-lg font-bold text-falaj-deep"><TrendingUp size={18} /> تغييرات تقدم المراحل</h2>{summary.progressUpdates.length === 0 ? <p className="rounded-xl border border-line bg-paper p-4 text-xs text-muted">لم تُسجّل تعديلات على تقدم المراحل خلال هذه الفترة.</p> : <div className="space-y-3">{summary.progressUpdates.map((update) => <div key={update.id} className="rounded-xl border border-line bg-paper p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-falaj-deep">{update.title}</strong><span className="font-mono text-xs font-bold text-falaj">{update.previousProgressPercent}% ← {update.nextProgressPercent}%</span></div><p className="mt-2 text-xs text-muted">{update.reason}</p><p className="mt-2 text-[11px] text-muted">{new Date(update.changedAt).toLocaleString("ar-OM")}</p></div>)}</div>}</article><article className="rounded-3xl border border-line bg-white p-6"><h2 className="mb-4 flex items-center gap-2 font-kufi text-lg font-bold text-falaj-deep"><FileCheck2 size={18} /> الإصدارات المنشورة</h2>{summary.publishedVersions.length === 0 ? <p className="rounded-xl border border-line bg-paper p-4 text-xs text-muted">لم يُنشر إصدار جديد للمستثمرين خلال هذه الفترة.</p> : <div className="space-y-3">{summary.publishedVersions.map((version) => <div key={version.id} className="rounded-xl border border-line bg-paper p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-falaj-deep">{version.title}</strong><span className="font-mono text-xs font-bold text-falaj">{version.versionTag}</span></div><p className="mt-2 text-xs leading-relaxed text-muted">{version.summary}</p><p className="mt-2 text-[11px] text-muted">نُشر في {new Date(version.publishedAt).toLocaleString("ar-OM")}</p></div>)}</div>}</article></section></>}
      </main>
    </div>
  );
}
