import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts'
import { Map, Sprout, TrendingUp, DollarSign, MapPin } from 'lucide-react'
import { StatCard } from '../components/StatCard'
import { Badge } from '../components/Badge'
import { regions, stats, farms } from '../data/all'
const COLS=['var(--teal)','var(--gold)','var(--indigo)','var(--green)','var(--red)']
const cd=regions.map(r=>({name:r.name,'المساحة':parseInt(r.cult.replace(/,/g,''))}))
const pd=regions.map(r=>({name:r.name,value:parseInt(r.cult.replace(/,/g,''))}))

export default function DashboardPage(){return <div style={{maxWidth:1280,margin:'0 auto',padding:'32px 24px',display:'flex',flexDirection:'column',gap:28}}>
<div><h1 className="page-h1">🇴🇲 لوحة التحكم</h1><p className="page-sub">نظرة عامة شاملة على المشروع الزراعي الوطني — 2025/2026</p></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(230px,1fr))',gap:16}}>
  {[{l:'إجمالي المساحة',v:stats.totalArea,u:'هكتار',i:Map,c:'var(--teal)',ch:'المساحة الكلية'},{l:'المساحة المزروعة',v:stats.totalCult,u:'هكتار',i:Sprout,c:'var(--green)',ch:'+18% سنوياً'},{l:'مناطق نشطة',v:'3',u:'من 5',i:TrendingUp,c:'var(--gold)',ch:'60% مفعلة'},{l:'إجمالي الاستثمار',v:stats.investment,u:'ر.ع',i:DollarSign,c:'var(--indigo)',ch:stats.investmentUSD}].map((s,i)=><StatCard key={i} {...s}/>)}</div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(420px,1fr))',gap:24}}>
  <div className="card" style={{padding:24}}><h3 style={{fontSize:16,fontWeight:700,marginBottom:20,display:'flex',alignItems:'center',gap:8,color:'var(--teal)'}}><MapPin size={18}/> المساحات المزروعة حسب المنطقة</h3><ResponsiveContainer width="100%" height={300}><BarChart data={cd} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="var(--border)" horizontal={false}/><XAxis type="number" tick={{fontSize:11}}/><YAxis dataKey="name" type="category" tick={{fontSize:12,fontWeight:500}} width={90}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid var(--border)',fontFamily:'Kanit',fontSize:13}}/><Bar dataKey="المساحة" radius={[0,8,8,0]} fill="var(--teal)" barSize={22}/></BarChart></ResponsiveContainer></div>
  <div className="card" style={{padding:24,display:'flex',flexDirection:'column',alignItems:'center'}}><h3 style={{fontSize:16,fontWeight:700,marginBottom:16,color:'var(--teal)'}}>النسب المئوية للمساحات</h3><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={pd} cx="50%" cy="50%" innerRadius={60} outerRadius={100} paddingAngle={4} dataKey="value">{pd.map((_,i)=><Cell key={i} fill={COLS[i]} stroke="white" strokeWidth={2}/>)}</Pie><Tooltip contentStyle={{borderRadius:12,border:'1px solid var(--border)',fontFamily:'Kanit',fontSize:13}}/></PieChart></ResponsiveContainer><div style={{display:'flex',flexWrap:'wrap',justifyContent:'center',gap:14,marginTop:12,fontSize:12}}>{regions.map((r,i)=><div key={i} style={{display:'flex',alignItems:'center',gap:6}}><div style={{width:10,height:10,borderRadius:2,background:COLS[i]}}/>{r.name}</div>)}</div></div></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(420px,1fr))',gap:24}}>
  <div className="card" style={{padding:20,overflowX:'auto'}}><h3 style={{fontSize:16,fontWeight:700,marginBottom:16,color:'var(--teal)',display:'flex',alignItems:'center',gap:8}}><Map size={16}/> المناطق الزراعية</h3><table className="table" style={{fontSize:13}}><thead><tr>{['المنطقة','المساحة','المزروع','نسبة','الحالة'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{regions.map(r=><tr key={r.id}><td style={{fontWeight:600}}>{r.name}</td><td style={{color:'var(--text2)'}}>{r.area}</td><td>{r.cult}</td><td><div style={{width:55,height:5,background:'var(--border)',borderRadius:3,overflow:'hidden'}}><div style={{width:`${Math.min(parseInt(r.cult.replace(/,/g,''))/600,100)}%`,height:'100%',background:'var(--teal)',borderRadius:3}}/></div></td><td><Badge label={r.status}/></td></tr>)}</tbody></table></div>
  <div className="card" style={{padding:20,overflowX:'auto'}}><h3 style={{fontSize:16,fontWeight:700,marginBottom:16,color:'var(--teal)',display:'flex',alignItems:'center',gap:8}}><Sprout size={16}/> المزارع النموذجية</h3><table className="table" style={{fontSize:13}}><thead><tr>{['المزرعة','المساحة','ماء/يوم','سنة التأسيس','الحالة'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{farms.map((f,i)=><tr key={i}><td style={{fontWeight:600}}>{f.name}</td><td>{f.area} هـ</td><td style={{color:'var(--text2)'}}>{f.water} م³</td><td style={{color:'var(--text2)'}}>{f.year}</td><td><Badge label={f.status}/></td></tr>)}</tbody></table></div></div></div>}