import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend } from 'recharts';import { costData } from '../data/all'
const tS=costData.setup.reduce((s:any,x:any)=>s+x.amt,0);const tO=costData.ops.reduce((s:any,x:any)=>s+x.amt,0)
const COLORS=['var(--teal)','var(--gold)','var(--indigo)','var(--green)','var(--red)','#10b981']

export default function ReportsPage(){return <div style={{maxWidth:1280,margin:'0 auto',padding:'32px 24px',display:'flex',flexDirection:'column',gap:28}}>
<div><h1 className="page-h1">📊 التقارير ودراسة الجدوى</h1><p className="page-sub">نموذج مزرعة 100 هكتار — منطقة النجد، محافظة ظفار</p></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(200px,1fr))',gap:16}}>
{[{l:'التكاليف التأسيسية',v:`${tS.toLocaleString()} ر.ع`,c:'var(--gold)',bg:'var(--gold-light)',border:'var(--gold)'},{l:'التكاليف التشغيلية',v:`${tO.toLocaleString()} ر.ع`,c:'var(--indigo)',bg:'var(--indigo-light)',border:'var(--indigo)'},{l:'الإجمالي',v:`${(tS+tO).toLocaleString()} ر.ع`,c:'var(--teal)',bg:'var(--teal-light)',border:'var(--teal)'},{l:'ما يعادل (~)',v:'$819,000',c:'var(--green)',bg:'var(--green-light)',border:'var(--green)'}].map((c,i)=><div key={i} className="card" style={{padding:22,textAlign:'center',background:c.bg,borderTop:`4px solid ${c.border}`}}><div style={{fontSize:13,color:'var(--text2)',marginBottom:10}}>{c.l}</div><div style={{fontSize:'1.5rem',fontWeight:800,color:c.c}}>{c.v}</div></div>)}</div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(460px,1fr))',gap:24}}>
{[costData.setup,costData.ops].map((cat,ci)=><div key={ci} className="card" style={{padding:24}}>
<h3 style={{fontSize:17,fontWeight:700,marginBottom:16,color:ci===0?'var(--gold)':'var(--indigo)'}}>{ci===0?'📋 التكاليف التأسيسية':'📋 التكاليف التشغيلية (موسم واحد)'}</h3>
<table style={{width:'100%',borderCollapse:'collapse',fontSize:14,marginBottom:20}}><thead><tr style={{borderBottom:'2px solid var(--border)'}}><th style={{textAlign:'right',padding:'8px 4px',color:'var(--text3)',fontWeight:600,fontSize:12}}>البند</th><th style={{textAlign:'left',padding:'8px 4px',color:'var(--text3)',fontWeight:600,fontSize:12}}>المبلغ (ر.ع)</th></tr></thead><tbody>{cat.map((x:any,j:number)=><tr key={j} style={{borderBottom:'1px solid var(--border)'}}><td style={{padding:'10px 4px'}}>{x.item}</td><td style={{padding:'10px 4px',textAlign:'left',fontFamily:'monospace'}}>{x.amt.toLocaleString()}</td></tr>)}<tr style={{fontWeight:700}}><td style={{padding:'12px 4px',borderTop:'2px solid var(--border)'}}>الإجمالي</td><td style={{padding:'12px 4px',textAlign:'left',fontFamily:'monospace',borderTop:'2px solid var(--border)',color:ci===0?'var(--gold)':'var(--indigo)'}}>{cat.reduce((s:any,x:any)=>s+x.amt,0).toLocaleString()}</td></tr></tbody></table>
<ResponsiveContainer width="100%" height={200}><PieChart><Pie data={cat.map((x:any)=>({name:x.item,value:x.amt}))} cx="50%" cy="50%" outerRadius={75} dataKey="value">{[...Array(6)].map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip contentStyle={{borderRadius:12,border:'1px solid var(--border)',fontFamily:'Kanit',fontSize:12}}/><Legend wrapperStyle={{fontSize:11,fontFamily:'Kanit'}}/></PieChart></ResponsiveContainer></div>)}</div></div>}