import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs"
import { regions } from "../data/regions"
import { farms } from "../data/farms"
import { formatCurrency, formatNumber } from "../lib/utils"

const costs = [{item:"تجهيز الأرض",amount:15000},{item:"حفر الآبار",amount:40000},{item:"محطة شمسية + تحلية",amount:80000},{item:"أنظمة الري",amount:55000},{item:"مبانٍ + مخازن",amount:25000},{item:"معدات زراعية",amount:60000}]
const ops = [{item:"بذور طبيعية",amount:8000},{item:"أسمدة عضوية",amount:12000},{item:"أجور عمالة",amount:15000},{item:"صيانة وتشغيل",amount:5000}]
const ts=costs.reduce((s,c)=>s+c.amount,0)
const to=ops.reduce((s,c)=>s+c.amount,0)

export default function ReportsPage() {
  return (<div className="space-y-6"><div><h1 className="text-2xl font-bold tracking-tight">التقارير والتحليلات</h1><p className="text-muted-foreground">دراسة الجدوى — نموذج مزرعة 100 هكتار في النجد</p></div>
  <Tabs defaultValue="feasibility"><TabsList><TabsTrigger value="feasibility">دراسة الجدوى</TabsTrigger><TabsTrigger value="regions">تحليل المناطق</TabsTrigger><TabsTrigger value="farms">ملخص المزارع</TabsTrigger></TabsList>
  <TabsContent value="feasibility" className="space-y-6"><div className="grid gap-4 md:grid-cols-4"><Card className="bg-gradient-to-b from-amber-500/10"><CardHeader className="pb-2"><CardTitle className="text-sm">التأسيسية</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold text-amber-600">{formatCurrency(ts)}</div></CardContent></Card><Card className="bg-gradient-to-b from-blue-500/10"><CardHeader className="pb-2"><CardTitle className="text-sm">التشغيلية</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold text-blue-600">{formatCurrency(to)}</div></CardContent></Card><Card className="bg-gradient-to-b from-emerald-500/10"><CardHeader className="pb-2"><CardTitle className="text-sm">الإجمالي</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold text-emerald-600">{formatCurrency(ts+to)}</div></CardContent></Card><Card className="bg-gradient-to-b from-purple-500/10"><CardHeader className="pb-2"><CardTitle className="text-sm">بالدولار</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold text-purple-600">$819,000</div></CardContent></Card></div><div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle>تأسيسية</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>البند</TableHead><TableHead className="text-left">المبلغ</TableHead></TableRow></TableHeader><TableBody>{costs.map(c=>(<TableRow key={c.item}><TableCell>{c.item}</TableCell><TableCell className="text-left font-mono">{formatCurrency(c.amount)}</TableCell></TableRow>))}<TableRow className="font-bold"><TableCell>الإجمالي</TableCell><TableCell className="text-left">{formatCurrency(ts)}</TableCell></TableRow></TableBody></Table></CardContent></Card><Card><CardHeader><CardTitle>تشغيلية</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>البند</TableHead><TableHead className="text-left">المبلغ</TableHead></TableRow></TableHeader><TableBody>{ops.map(c=>(<TableRow key={c.item}><TableCell>{c.item}</TableCell><TableCell className="text-left font-mono">{formatCurrency(c.amount)}</TableCell></TableRow>))}<TableRow className="font-bold"><TableCell>الإجمالي</TableCell><TableCell className="text-left">{formatCurrency(to)}</TableCell></TableRow></TableBody></Table></CardContent></Card></div></TabsContent>
  <TabsContent value="regions"><Card><CardHeader><CardTitle>تحليل المناطق</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>المنطقة</TableHead><TableHead>إجمالي</TableHead><TableHead>مزروع</TableHead><TableHead>نسبة</TableHead><TableHead>الحالة</TableHead></TableRow></TableHeader><TableBody>{regions.map(r=>{const p=((r.cultivatedAreaHa/r.totalAreaHa)*100).toFixed(1);return(<TableRow key={r.id}><TableCell className="font-medium">{r.name}</TableCell><TableCell>{formatNumber(r.totalAreaHa)}</TableCell><TableCell>{formatNumber(r.cultivatedAreaHa)}</TableCell><TableCell>{p}%</TableCell><TableCell>{r.status}</TableCell></TableRow>)})}</TableBody></Table></CardContent></Card></TabsContent>
  <TabsContent value="farms"><Card><CardHeader><CardTitle>ملخص المزارع</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>المزرعة</TableHead><TableHead>المساحة</TableHead><TableHead>الماء/يوم</TableHead><TableHead>التأسيس</TableHead><TableHead>الحالة</TableHead></TableRow></TableHeader><TableBody>{farms.map(f=>(<TableRow key={f.id}><TableCell className="font-medium">{f.name}</TableCell><TableCell>{f.areaHa} هكتار</TableCell><TableCell>{f.waterConsumptionDaily} م³</TableCell><TableCell>{f.establishedYear}</TableCell><TableCell>{f.status}</TableCell></TableRow>))}</TableBody></Table></CardContent></Card></TabsContent></Tabs></div>)
}