import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend } from 'recharts'
import { costData } from '../data/farms'
const tS=costData.setup.reduce((s:any,x:any)=>s+x.amt,0)
const tO=costData.ops.reduce((s:any,x:any)=>s+x.amt,0)
const COLS=['var(--teal)','var(--gold)','var(--indigo)','var(--green)','var(--red)','#10b981']

export default function ReportsPage(){return <div style={{maxWidth:1280,margin:'0 auto',padding:'32px 24px',display:'flex',flexDirection:'column',gap:32}}>
<div><h1 style={{fontSize:28,fontWeight:800,color:'var(--teal)'}}>📊 التقارير ودراسة الجدوى</h1><p style={{color:'var(--text-secondary)',marginTop:4}}>نموذج مزرعة 100 هكتار — منطقة النجد، ظفار</p></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill, minmax(200px, 1fr))',gap:16}}>
{[{l:'التأسيسية',v:`${tS.toLocaleString()} ر.ع`,c:'var(--gold)',b:'var(--gold-light)'},{l:'التشغيلية (موسم)',v:`${tO.toLocaleString()} ر.ع`,c:'var(--indigo)',b:'var(--indigo-light)'},{l:'الإجمالي',v:`${(tS+tO).toLocaleString()} ر.ع`,c:'var(--teal)',b:'var(--teal-light)'},{l:'بالدولار (~)',v:'$819,000',c:'var(--green)',b:'var(--green-light)'}].map((c,i)=><div key={i} className="card" style={{padding:24,textAlign:'center',background:c.b,borderTop:`4px solid ${c.c}`}}><div style={{fontSize:14,color:'var(--text-secondary)',marginBottom:8}}>{c.l}</div><div style={{fontSize:24,fontWeight:800,color:c.c}}>{c.v}</div></div>)}
</div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(400px, 1fr))',gap:24}}>
{[costData.setup,costData.ops].map((cat,ci)=><div key={ci} className="card" style={{padding:24}}><h3 style={{fontSize:16,fontWeight:700,marginBottom:16,color:ci===0?'var(--gold)':'var(--indigo)'}}>{ci===0?'التكاليف التأسيسية':'التكاليف التشغيلية (موسم واحد)'}</h3><table style={{width:'100%',fontSize:14,borderCollapse:'collapse',marginBottom:24}}><thead><tr style={{borderBottom:'2px solid var(--border)'}}><th style={{textAlign:'right',padding:'8px 4px',color:'var(--text-muted)',fontWeight:600}}>البند</th><th style={{textAlign:'left',padding:'8px 4px',color:'var(--text-muted)',fontWeight:600}}>المبلغ (ر.ع)</th></tr></thead><tbody>{cat.map((x:any,j:number)=><tr key={j} style={{borderBottom:'1px solid var(--border)'}}><td style={{padding:'10px 4px'}}>{x.item}</td><td style={{padding:'10px 4px',textAlign:'left',fontFamily:'monospace'}}>{x.amt.toLocaleString()}</td></tr>)}<tr style={{fontWeight:700}}><td style={{padding:'12px 4px',borderTop:'2px solid var(--border)'}}>الإجمالي</td><td style={{padding:'12px 4px',textAlign:'left',fontFamily:'monospace',borderTop:'2px solid var(--border)',color:ci===0?'var(--gold)':'var(--indigo)'}}>{cat.reduce((s:any,x:any)=>s+x.amt,0).toLocaleString()}</td></tr></tbody></table><ResponsiveContainer width="100%" height={200}><PieChart><Pie data={cat.map((x:any)=>({name:x.item,value:x.amt}))} cx="50%" cy="50%" outerRadius={80} dataKey="value">{[...Array(6)].map((_,i)=><Cell key={i} fill={COLS[i]}/>)}</Pie><Tooltip contentStyle={{borderRadius:12,border:'1px solid var(--border)',fontFamily:'Kanit',fontSize:12}}/><Legend wrapperStyle={{fontSize:11,fontFamily:'Kanit'}}/></PieChart></ResponsiveContainer></div>)}</div>
</div>}