import { Mail, Phone, Github, Globe, Shield, Database, Leaf } from 'lucide-react'

export default function SettingsPage() {
  return <div className="max-w-2xl mx-auto px-4 sm:px-6 py-8 space-y-6">
    <div><h1 className="text-2xl sm:text-3xl font-bold text-gray-900">⚙️ الإعدادات</h1><p className="text-gray-400 mt-1">الملف الشخصي ومعلومات النظام</p></div>
    <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100 space-y-4">
      <div className="flex items-center gap-4 pb-4 border-b border-gray-100"><img src="/logo2040.png" className="w-16 h-16 rounded-xl object-contain border border-gray-100" alt="" /><div><h3 className="font-bold text-lg">سهيل عارف قائد أحمد الحكيمي</h3><p className="text-sm text-gray-400">مدير النظام — باحث في الأمن الغذائي</p><span className="inline-block mt-1 px-3 py-0.5 rounded-full text-xs font-medium bg-green-50 text-green-700">Admin</span></div></div>
      <div className="grid sm:grid-cols-2 gap-4 text-sm"><div className="space-y-1"><label className="text-gray-400 text-xs">البريد الإلكتروني</label><div className="flex items-center gap-2"><Mail size={14} className="text-green-600" /> suhailarfe@gmail.com</div></div><div className="space-y-1"><label className="text-gray-400 text-xs">الهاتف</label><div className="flex items-center gap-2"><Phone size={14} className="text-green-600" /> 00967736986271</div></div><div className="space-y-1"><label className="text-gray-400 text-xs">GitHub</label><div className="flex items-center gap-2"><Github size={14} className="text-green-600" /> github.com/suhailarfe</div></div><div className="space-y-1"><label className="text-gray-400 text-xs">الموقع</label><div className="flex items-center gap-2"><Globe size={14} className="text-green-600" /> suhailarfe.github.io/oman-agri-system</div></div></div>
    </div>
    <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100 space-y-4 text-sm"><div className="flex justify-between items-center"><div className="flex items-center gap-2"><Database size={16} className="text-green-600" />قاعدة البيانات</div><span className="text-gray-400">SQL — 7 جداول مترابطة</span></div><hr className="border-gray-100" /><div className="flex justify-between items-center"><div className="flex items-center gap-2"><Shield size={16} className="text-green-600" />الصلاحيات</div><span className="text-gray-400">Admin / Farmer / Supplier</span></div><hr className="border-gray-100" /><div className="flex justify-between items-center"><div className="flex items-center gap-2"><Leaf size={16} className="text-green-600" />الإصدار</div><span className="text-gray-400">1.0.0 — 2025/2026م</span></div></div>
  </div>
}